FROM ubuntu:22.04

RUN useradd -u 9999 non-root

RUN mkdir -p home/non-root
RUN mkdir -p home/non-root/container_tmp

RUN apt update && apt install -y python3 pip nano

COPY requirements.txt home/non-root/requirements.txt
COPY data/training_data.npy home/non-root/training_data.npy
COPY .hidden/security.py home/non-root/security.py
COPY .hidden/bad_argvals.txt home/non-root/bad_argvals.txt

RUN pip install -r home/non-root/requirements.txt

RUN chmod +x home/non-root/security.py

USER non-root

